# Generated by Django 4.2.21 on 2025-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0003_ativo_usuario_alter_ativo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ticker',
            field=models.CharField(max_length=20),
        ),
    ]
