# Generated by Django 4.2.21 on 2025-05-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0004_alter_ativo_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('operacao', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('BONIFICACAO', 'Bonificação'), ('GRUPAMENTO', 'Grupamento'), ('DESDOBRAMENTO', 'Desdobramento')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=15)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('custoTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativo.ativo')),
            ],
            options={
                'ordering': ['-data', '-dataCriacao'],
            },
        ),
    ]
