# Generated by Django 4.2.21 on 2025-05-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0005_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativo.ativo')),
            ],
            options={
                'verbose_name': 'Dividendo',
                'verbose_name_plural': 'Dividendos',
                'ordering': ['-data', '-dataCriacao'],
            },
        ),
    ]
