# Generated by Django 4.2.21 on 2025-05-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0006_dividendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucaoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativo.ativo')),
            ],
            options={
                'ordering': ['-data', 'ativo__ticker'],
                'unique_together': {('ativo', 'data')},
            },
        ),
    ]
