# Generated by Django 4.2.21 on 2025-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0007_evolucaopatrimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaopatrimonial',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
