# Generated by Django 4.2.21 on 2025-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0008_evolucaopatrimonial_custo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='anotacao',
            field=models.TextField(blank=True, help_text='Anotações gerais sobre o ativo'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='dataVencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento para investimentos de renda fixa', null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem desejada do total (0-100)', max_digits=5),
        ),
    ]
