# Generated by Django 4.2.21 on 2025-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0009_ativo_anotacao_ativo_datavencimento_ativo_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaopatrimonial',
            name='dividendos_mes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de dividendos recebidos neste mês para este ativo', max_digits=10),
        ),
    ]
