# Generated by Django 4.2.21 on 2025-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0010_add_dividendos_mes_to_evolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='icone_url',
            field=models.URLField(blank=True, help_text='URL do ícone do ativo', null=True),
        ),
    ]
