# Generated by Django 4.2.21 on 2025-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0011_ativo_icone_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='preco_medio',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Preço médio atual do ativo', max_digits=15),
        ),
        migrations.AddField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Quantidade atual do ativo', max_digits=15),
        ),
    ]
