# Generated by Django 4.2.21 on 2025-06-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0012_ativo_preco_medio_ativo_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_preco_estimado', models.BooleanField(default=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativo.ativo')),
            ],
            options={
                'ordering': ['-data', '-dataCriacao'],
                'unique_together': {('ativo', 'data')},
            },
        ),
    ]
