# Generated by Django 4.2.21 on 2025-06-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0014_add_valor_atual_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativo.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subtipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PrecoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('moeda', models.CharField(max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_estimado', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'moeda'], name='ativo_preco_ticker_ba481b_idx'), models.Index(fields=['data_atualizacao'], name='ativo_preco_data_at_fd5003_idx')],
                'unique_together': {('ticker', 'moeda')},
            },
        ),
    ]
